version: "3.9"
services:
  sensor-fleet:
    container_name: sensor-fleet
    build: sensor-fleet
    environment:
      AWS_ACCESS_KEY_ID: some_key_id
      AWS_SECRET_ACCESS_KEY: some_secret
    depends_on:
      - localstack

  preprocessor:
    container_name: preprocessor
    build: preprocessor
    environment:
      DEBUG: svc:*
    depends_on:
      - localstack

  localstack:
    container_name: "localstack"
    build: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
